# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_Wiedervorlage_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reminder',
            field=models.DateField(default='1970-01-01', verbose_name='WV'),
        ),
    ]
